
import { VoiceName, Gender, VoiceOption } from './types';

export const DEFAULT_VOICES: VoiceOption[] = [
  {
    id: 'default-kore',
    apiId: VoiceName.Kore,
    name: 'Kore',
    gender: Gender.Female,
    description: 'Calm, soothing, and precise. Perfect for assistants.',
    color: 'from-pink-500 to-purple-500',
    speed: 1.0,
    pitch: 0,
  },
  {
    id: 'default-puck',
    apiId: VoiceName.Puck,
    name: 'Puck',
    gender: Gender.Male,
    description: 'Playful, energetic, and distinct. Good for storytelling.',
    color: 'from-cyan-400 to-blue-500',
    speed: 1.0,
    pitch: 0,
  },
  {
    id: 'character-dracula',
    apiId: VoiceName.Fenrir,
    name: 'Count Dracula',
    gender: Gender.Male,
    description: 'Ancient, theatrical, and blood-curdling. The Count’s own resonance.',
    color: 'from-red-900 to-slate-900',
    speed: 0.85,
    pitch: -550,
  },
  {
    id: 'character-ghost',
    apiId: VoiceName.Zephyr,
    name: 'The Ghost',
    gender: Gender.Neutral,
    description: 'Whispering from the beyond. An ethereal, hauntological presence.',
    color: 'from-slate-400 to-indigo-300',
    speed: 1.2,
    pitch: 500,
  },
  {
    id: 'default-fenrir',
    apiId: VoiceName.Fenrir,
    name: 'Fenrir',
    gender: Gender.Male,
    description: 'Deep, resonant, and authoritative. Ideal for command.',
    color: 'from-red-500 to-orange-600',
    speed: 1.0,
    pitch: 0,
  },
  {
    id: 'default-zephyr',
    apiId: VoiceName.Zephyr,
    name: 'Zephyr',
    gender: Gender.Neutral,
    description: 'Soft, airy, and balanced. Great for therapy or meditation.',
    color: 'from-emerald-400 to-teal-500',
    speed: 1.0,
    pitch: 0,
  },
  {
    id: 'default-charon',
    apiId: VoiceName.Charon,
    name: 'Charon',
    gender: Gender.Male,
    description: 'Steady, reliable, and grounded. Suitable for news.',
    color: 'from-violet-500 to-indigo-600',
    speed: 1.0,
    pitch: 0,
  },
  {
    id: 'preset-luna',
    apiId: VoiceName.Kore,
    name: 'Luna',
    gender: Gender.Female,
    description: 'Deep, slow, and mystical. Great for fantasy narration.',
    color: 'from-indigo-400 to-purple-600',
    speed: 0.9,
    pitch: -200,
  },
];

export const DEFAULT_INSTRUCTION = "You are a helpful, futuristic AI assistant living in a holographic interface. You are concise, intelligent, and slightly witty.";
